fastlane_version "2.5.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods    
  end

  desc "Deploy a new version to the App Store and send a testflight build."
  lane :release do
    gym(scheme: "IceGig")
    pilot
    deliver(force: true)
  end
end